services:
  frontend:
    build:
      context: ./frontend/hexacode-playground
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map React to port 3000 on the host
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map Flask to port 5000 on the host
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    restart: always
    depends_on:
      - frontend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount custom NGINX config
    ports:
      - "80:80"  # Expose NGINX on port 80
    depends_on:
      - frontend
      - backend
